version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application"
          command: dotnet.exe build src\prosek.sln --configuration Release
workflows:
  test_and_build:
    jobs:
      - build
